### PR TITLE
Can I add my bot

### PR DESCRIPTION
**Pull request by skybird23333**
#3

### CODE REVIEW

**Comment by insertish** [comment]
Link is dead.

**Comment by skybird23333** [comment]
uh oh

>

**Comment by skybird23333** [comment]
**thonk.skybird.ga** should work - I still have some issues with the github repo and I will publish that soon.

**Review by orsou — CHANGES_REQUESTED** [review]
> thonk.skybird.ga

That links to a site called **"gdzjq.made4fcuck.net"** which is an scam-site based on adult content.

**Comment by skybird23333** [comment]
> > thonk.skybird.ga
> 
> That links to a site called **"gdzjq.made4fcuck.net"** which is an scam-site based on adult content.

I no longer own the domain, freenom has taken it away and I cannot control the content on it anymore. Please don't visit that link.

**Comment by insertish** [comment]
https://user-images.githubusercontent.com/38285861/164206035-fa9e27d2-4e11-4e77-8a63-c07f87d6efc5.mp4

**Comment by janderedev** [comment]
D73E42FD-7F41-4EE4-9133-78E2B2090A32

**Comment by williambl** [comment]
so true

**Comment by skybird23333** [comment]
图片

**Pull request closed without merging**
